name: OpenRouter PR Agent
on:
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: startswith(github.event.comment.body, '/ask-agent')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run CodiumAI PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI.KEY: ${{ secrets.OPENROUTER_KEY }}
          OPENAI.API_BASE: "https://openrouter.ai"
          PR_AGENT.CUSTOM_MODEL: "google/gemini-2.5-flash:free"
